# Generated by Django 5.0.3 on 2024-04-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_name_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='message',
            field=models.CharField(default='test msg', max_length=100, verbose_name='Сообщение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.CharField(default='100', max_length=100, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
    ]
